apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:  # specification of the pod's contents
  restartPolicy: Never
  containers:
  - name: benchmark
    image: "jfeinauer/test123"
    imagePullPolicy: Always
    command: ["python", "run.py"]
  - name: run-torch
    image: "jfeinauer/test123"
    imagePullPolicy: Always
    command: ["python", "run_torch.py"]
  - name: run-onnx
    image: "jfeinauer/test123"
    imagePullPolicy: Always
    command: [ "python", "run_onnx.py" ]
