apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:  # specification of the pod's contents
  restartPolicy: Never
  containers:
  - name: hello
    image: "jfeinauer/test123"
    # command: ["time", "-v", "python", "run.py"]
    env:
    - name: API_KEY
      value: "127d2ac875f6c260ad662432fe290e5ef8c502d3"
